name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: fix
      run: chmod +x premake5 && sudo apt install xorg-dev
    
    - name: build
      run: ./premake5 gmake2 && make
